"use client";
import { useCallback, useEffect, useState } from "react";
import { AdminCard } from "@/components/admin/layout";
import AdminTripMap from "@/components/admin/AdminTripMap";

type Station = { _id: string; objectId: number; name: string; direction: string; zones: string; description: string; landmark: string; stationType: string; lat: number; lng: number; active: boolean };
const input = { border: "1px solid var(--color-border)", borderRadius: 8, padding: "9px 10px", fontSize: 14 } as const;
const button = { border: 0, borderRadius: 8, padding: "9px 12px", fontWeight: 700, background: "var(--color-primary)", color: "var(--color-on-primary)", cursor: "pointer" } as const;

export default function StationManagement({ regionCode }: { regionCode: string }) {
  const [stations, setStations] = useState<Station[]>([]); const [query, setQuery] = useState(""); const [message, setMessage] = useState<string | null>(null);
  const [form, setForm] = useState<Record<string, string>>({ objectId: "", name: "", direction: "", zones: "", description: "", landmark: "", stationType: "", lat: "", lng: "" });
  const request = useCallback(async (url: string, init?: RequestInit) => { const glue = url.includes("?") ? "&" : "?"; const res = await fetch(`${url}${glue}region=${encodeURIComponent(regionCode)}`, init); const json = await res.json().catch(() => ({})); if (!res.ok) throw new Error(json.error ?? "Station request failed."); return json; }, [regionCode]);
  const load = useCallback(async () => { try { const data = await request(`/api/admin/stations?q=${encodeURIComponent(query)}&limit=100`); setStations(data.stations ?? []); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not load stations."); } }, [query, request]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function create(e: React.FormEvent) { e.preventDefault(); try { await request("/api/stations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, objectId: Number(form.objectId), lat: Number(form.lat), lng: Number(form.lng) }) }); setMessage("Station created."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not create station."); } }
  async function toggle(station: Station) { try { await request(`/api/stations/${station.objectId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !station.active }) }); setMessage(`Station ${station.active ? "deactivated" : "reactivated"}.`); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not update station."); } }
  return <div style={{ display: "grid", gap: 20 }}><AdminCard title="Station management" description={`Create, search, deactivate, and reactivate stations for ${regionCode}.`}><form onSubmit={create} style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 10 }}>{Object.entries(form).map(([key, value]) => <input key={key} style={input} required value={value} placeholder={key} type={key === "lat" || key === "lng" || key === "objectId" ? "number" : "text"} onChange={(e) => setForm((current) => ({ ...current, [key]: e.target.value }))} />)}<button style={button}>Create station</button></form>{message && <p role="status">{message}</p>}</AdminCard><AdminCard title="Station map" description="Current results for the selected region."><AdminTripMap points={stations.map((station) => ({ lat: station.lat, lng: station.lng, label: `#${station.objectId} ${station.name}`, kind: "station" as const }))} /></AdminCard><AdminCard title="Station list" description="Search by object ID, name, landmark, or zone."><div style={{ display: "flex", gap: 10, marginBottom: 14 }}><input style={{ ...input, flex: 1 }} value={query} placeholder="Search stations" onChange={(e) => setQuery(e.target.value)} /><button style={button} onClick={() => void load()}>Search</button></div><div style={{ overflowX: "auto" }}><table className="admin-table" style={{ width: "100%", borderCollapse: "separate", borderSpacing: 0 }}><thead><tr>{["ID", "Name", "Type", "Zone", "Coordinates", "Status", "Action"].map((head) => <th key={head} style={{ padding: "11px 12px", textAlign: "left" }}>{head}</th>)}</tr></thead><tbody>{stations.map((station) => <tr key={station._id}><td style={{ padding: "10px 12px" }}>{station.objectId}</td><td style={{ padding: "10px 12px" }}>{station.name}</td><td style={{ padding: "10px 12px" }}>{station.stationType}</td><td style={{ padding: "10px 12px" }}>{station.zones}</td><td style={{ padding: "10px 12px" }}>{station.lat.toFixed(5)}, {station.lng.toFixed(5)}</td><td style={{ padding: "10px 12px" }}>{station.active ? "Active" : "Inactive"}</td><td style={{ padding: "10px 12px" }}><button style={{ ...button, background: station.active ? "var(--color-danger)" : "var(--color-secondary)" }} onClick={() => void toggle(station)}>{station.active ? "Deactivate" : "Reactivate"}</button></td></tr>)}</tbody></table></div></AdminCard></div>;
}
